
title: Józef Podlecki
email: jozef.witold.podlecki@gmail.com

description: >
  Portfolio and blog
baseurl: "Jozefpodlecki.github.io"
url: "Jozefpodlecki.github.io"

social_links:
  github:  jozefpodlecki
  facebook: jozek.podlecki
  linkedin: jozef-witold-podlecki

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag